export enum USER_GETTERS {
  GET_IS_USER_LOGIN = "GET_IS_USER_LOGIN",
  GET_USER_INFO = "GET_USER_INFO",
}

export enum USER_SETTERS {
  SET_IS_USER_LOGIN = "SET_IS_USER_LOGIN",
  SET_USER_INFO = "SET_USER_INFO",
}
